spring.datasource.url=jdbc:mariadb://localhost:3308/entreprise_db?createDatabaseIfNotExist=true
spring.datasource.username=borel
spring.datasource.password=borel
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=8081
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs